---
services:
  gatus:
    image: twinproduction/gatus:latest
    env_file: ".env"
    container_name: gatus
    restart: unless-stopped
    environment:
      - PORT=${GATUS_PORT}
    network_mode: host
    ### use config.yaml to specify port
    ### defaults to 8080
    volumes:
      - ${DOCKER_PERSIST}/gatus/config:/config
      - ${DOCKER_PERSIST}/gatus/data:/data/
