-- TODO: learn the hilight mappings for git signs

-- vim.keymap.set({ "n", "v" }, "<leader>gh", "gitsigns", {
-- 	silent = true,
-- 	desc = "+hunks",
-- })
--
-- vim.keymap.set("n", "<leader>ghb", ":Gitsigns blame_line<CR>", {
-- 	silent = true,
-- 	desc = "Blame line",
-- })
--
-- vim.keymap.set("n", "<leader>ghd", ":Gitsigns diffthis<CR>", {
-- 	silent = true,
-- 	desc = "Diff This",
-- })
--
-- vim.keymap.set("n", "<leader>ghp", ":Gitsigns preview_hunk<CR>", {
-- 	silent = true,
-- 	desc = "Preview hunk",
-- })
--
-- vim.keymap.set("n", "<leader>ghR", ":Gitsigns reset_buffer<CR>", {
-- 	silent = true,
-- 	desc = "Reset Buffer",
-- })
--
-- vim.keymap.set({ "n", "v" }, "<leader>ghr", ":Gitsigns reset_hunk<CR>", {
-- 	true,
-- 	"Reset Hunk",
-- })
--
-- vim.keymap.set({ "n", "v" }, "<leader>ghs", ":Gitsigns stage_hunk<CR>", {
-- 	silent = true,
-- 	desc = "Stage Hunk",
-- })
--
-- vim.keymap.set("n", "<leader>ghS", ":Gitsigns stage_buffer<CR>", {
-- 	silent = true,
-- 	desc = "Stage Buffer",
-- })
--
-- vim.keymap.set("n", "<leader>ghu", ":Gitsigns undo_stage_hunk<CR>", {
-- 	silent = true,
-- 	desc = "Undo Stage Hunk",
-- })

-- local wk = require("which-key")
--
-- -- https://github.com/folke/which-key.nvim?tab=readme-ov-file#%EF%B8%8F-mappings
-- wk.register({
-- 	g = {
-- 		h = {
-- 			name = "hunk",
-- 			d = { "<cmd>Gitsigns diffthis<cr>", "Diff This" },
-- 		},
-- 	},
-- }, { prefix = "<leader>" })
