# Execute your favorite apps at launch

# # keep large LG monitor off since I don't need in tiling
exec-once = hyprctl dispatch dpms off DP-2

# # batch script for services
exec-once = bash ~/.config/hypr/hyprland/start.sh

# # individual apps (put here to ensure window-rules)
exec-once = obsidian &
exec-once = signal-desktop --start-in-tray &
exec-once = steam -silent &
# exec-once = blueberry-tray &

# # night light
exec-once = dbus-update-activation-environment --systemd HYPRLAND_INSTANCE_SIGNATURE
exec = hyprshade auto

# # todo: see if hyprctl can order foot / code order
# # note: windowrules seem to have higher priority than specifying with exec
# exec-once=[workspace 2 silent] foot zellij
exec-once=[workspace 2 silent] foot
exec-once=[workspace 2 silent] code
exec-once=[workspace 3 silent] microsoft-edge
exec-once=[workspace 4 silent] firefox

# # misc
exec-once = wl-paste -t text --watch clipman store --no-persist   ### what does this do?

# # hyprctl
# # env deson't seem to be doing cursor size so do it here
exec-once = hyprctl setcursor Bibata-Modern-Ice 40

