# # Execute your favorite apps at launch
# # batch script for services
# # (chezmoi filename for vim) ./executable_start.sh
exec-once = bash ~/.config/hypr/hyprland/start.sh

# # silent tray stuff
exec-once = signal-desktop --start-in-tray &
# exec-once = steam -silent &
# exec-once = blueberry-tray &

# # individual apps (let window-rules decide location)
exec-once = obsidian &
exec-once = microsoft-edge
exec-once = firefox
# # neovide does work with one-time to a workspace :/ window rule will do I guess
# exec-once = mkdir -p ~/tmp/notes && cd ~/tmp/notes && neovide

# # night light
exec-once = dbus-update-activation-environment --systemd HYPRLAND_INSTANCE_SIGNATURE
exec = hyprshade auto

# # todo: see if hyprctl can order foot / code order
# # note: windowrules seem to have higher priority than specifying with exec
exec-once=[workspace 2 silent] foot zellij
# exec-once=[workspace 2 silent] code

# # misc
exec-once = wl-paste -t text --watch clipman store --no-persist   ### what does this do?

# # hyprctl
# # env deson't seem to be doing cursor size so do it here
exec-once = hyprctl setcursor Bibata-Modern-Ice 40

