# See https://wiki.hyprland.org/Configuring/Monitors/
# # monitor=name,resolution,position,scale
# # hyprctl monitors all
monitor=,preferred,auto,auto

# # # GIGA-BYTE
# # # comma issue fixed in latest git , v0.3.8
monitor=DP-1, 2560x1440@170, -0x770, 1  # GIGA-BYTE M27Q, but commas causes syntax error. Fixed in v0.3.8 via shortdesc
# monitor=desc:LG SDQHD 208NTBK6R077, 2560x2880@60, 2560x0, 1
# # disable works if used with the right dispatch name (DP != desc)
monitor=DP-2,disable
