# # configure which workspaces belong to which monitor
# # hyprctl workspaces

# # TLDR don't mix workspace names and indexes. I don't get it.
# # defaultName and name *are* different. once again, do weird things
# # I'm not sure how to do fallbacks with dual monitors, that's for another day
# # names on workspaces by default have a negative undex (-1337 anybody?) ; can't seem to manually number them
# # try using waybar to display index and names for live debugging; or use hyprctl workspaces

# # "Disabling a monitor will literally remove it from the layout, moving all windows and workspaces to any remaining ones."
# # https://wiki.hyprland.org/Configuring/Monitors/


# # DP-1 : GIGA-BYTE M27Q
workspace = 1, monitor:DP-1, persistent:true
workspace = 2, monitor:DP-1, persistent:true

# # workspace 3 and 4 defined. overrulled by monitor 2 if it exists ; works really well!
workspace = 3, monitor:DP-1, persistent:true
workspace = 4, monitor:DP-1, persistent:true

# # T460 sei-asagiri
workspace = 1, monitor:desc:Chimei Innolux Corporation 0x14C9, persistent:true
workspace = 2, monitor:desc:Chimei Innolux Corporation 0x14C9, persistent:true
workspace = 3, monitor:desc:Chimei Innolux Corporation 0x14C9, persistent:true
workspace = 4, monitor:desc:Chimei Innolux Corporation 0x14C9, persistent:true
workspace = 5, monitor:desc:Chimei Innolux Corporation 0x14C9, persistent:true

# # DP-2 : LG SDQHD 208NTBK6R077 (vertical monitor)
workspace = 3, monitor:DP-2, gapsin:15, persistent:true
workspace = 4, monitor:DP-2, gapsin:15, persistent:true
