# env var
source = ~/.config/hypr/conf/themes/mocha.conf
source = ~/.config/hypr/conf/exec.conf
source = ~/.config/hypr/conf/env.conf
source = ~/.config/hypr/conf/windowrule.conf
source = ~/.config/hypr/conf/keybinds.conf
source = ~/.config/hypr/conf/monitor.conf
source = ~/.config/hypr/conf/style.conf
source = ~/.config/hypr/conf/misc.conf