# env var
source = ./hyprland/themes/mocha.conf
source = ./hyprland/exec.conf
source = ./hyprland/env.conf
source = ./hyprland/windowrule.conf
source = ./hyprland/workspacerule.conf
source = ./hyprland/keybinds.conf
source = ./hyprland/monitor.conf
source = ./hyprland/style.conf
source = ./hyprland/misc.conf

