# env var
source = ~/.config/hypr/conf/startup.conf
source = ~/.config/hypr/conf/env.conf
source = ~/.config/hypr/conf/windowrule.conf
source = ~/.config/hypr/conf/keybinds.conf
source = ~/.config/hypr/conf/monitor.conf
source = ~/.config/hypr/conf/style.conf
source = ~/.config/hypr/conf/misc.conf

general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    gaps_in = 5
    gaps_out = 5
    border_size = 1
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)

    layout = dwindle
    #no_border_on_floating = yes

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false
}