### must preload
preload=/home/archoo/Pictures/AnimeWallpaperSetV2/tall/giga-untitled_panorama2_final_46660435144_o.jpg
preload=/home/archoo/Pictures/AnimeWallpaperSetV2/landscape/giga-screenshot-58_final_47330603722_o.jpg

### set wallpaper to monitor
wallpaper = DP-1,/home/archoo/Pictures/AnimeWallpaperSetV2/tall/giga-untitled_panorama2_final_46660435144_o.jpg
wallpaper = DP-2,/home/archoo/Pictures/AnimeWallpaperSetV2/landscape/giga-screenshot-58_final_47330603722_o.jpg
