#? file: https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/keymap-default.toml
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
  { on = "?", run = "help", desc = "Open help" },
  { on = "!", run = 'shell "$SHELL" --block', desc = "Open shell here" },
  { on = "<C-o>", run = 'shell -- dragon -x -i -T "$1"' },
  { on = [
    "g",
    "r",
  ], run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"' },
]

[input]
prepend_keymap = [{ on = "<Esc>", run = "close", desc = "Cancel input" }]

[help]
append_keymap = [{ on = "/", run = "filter", desc = "Filter help items" }]
