theme = "custom"

[editor]
line-number = "relative"
auto-format = false
color-modes = true
bufferline = "multiple"
cursorline = true

[editor.file-picker]
hidden = false
git-exclude = false
follow-symlinks = true

### Keymaps
### https://github.com/LGUG2Z/helix-vim/blob/master/config.toml
[keys.normal]
"{" = ["goto_prev_paragraph", "extend_visual_line_up"]
"}" = ["goto_next_paragraph"]

0 = "goto_line_start"
"$" = "extend_to_line_end"                                     ### default: 'keep-pipe'?
"^" = "extend_to_line_start"
G = "goto_file_end"
"%" = ["match_brackets"]                                       ### default: select entire file -> equivalent : gg v ge
V = ["select_mode", "extend_to_line_bounds"]
D = ["extend_to_line_end"]
C-r = "redo"
C-s = ":w"                                                     ### default: save_selection
M = "save_selection"
left = "jump_view_left"
right = "jump_view_right"
up = "jump_view_up"
down = "jump_view_down"

### always i/a at current cursor position
i = ["collapse_selection", "insert_mode"]
a = ["collapse_selection", "append_mode"]

# Search for word under cursor
"*" = [
  "move_char_right",
  "move_prev_word_start",
  "move_next_word_end",
  "search_selection",
  "search_next",
]
"#" = [
  "move_char_right",
  "move_prev_word_start",
  "move_next_word_end",
  "search_selection",
  "search_prev",
]

### lazygit support with A-g
A-g = [
    ":write-all",
    ":new",
    ":insert-output lazygit",
    ":buffer-close!",
    ":redraw",
    ":reload-all"
]

# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal."space"]
"%" = "select_all"

[keys.select]
"{" = ["goto_prev_paragraph", "extend_visual_line_up"]
"}" = ["goto_next_paragraph"]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
D = ["extend_to_line_end"]
"%" = "match_brackets"
C-s = ":w"
M = "save_selection"
left = "jump_view_left"
right = "jump_view_right"
up = "jump_view_up"
down = "jump_view_down"

### always i/a at current cursor position
i = ["collapse_selection", "insert_mode"]
a = ["collapse_selection", "append_mode"]

# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
