### # to allow transparent terminal background
theme = "custom" # ~/.local/share/chezmoi/dot_config/helix/themes/custom.toml.tmpl

#? docs (vercel): https://helix-editor.vercel.app/configuration/editor
[editor]
line-number = "relative"
auto-format = false
color-modes = true       # display NOR INS SEL modes in lhs status bar
bufferline = "multiple"  # show bufferline (tabs) only if more than one buffer
cursorline = true

[editor.file-picker]
hidden = false      # allow hidden files
git-exclude = false # allow .git/info/exclude files

### Keymaps
#? inspiration: https://github.com/LGUG2Z/helix-vim/blob/master/config.toml
#? docs (vercel): https://helix-editor.vercel.app/reference/keymap
#? docs (main): https://docs.helix-editor.com/keymap.html
[keys.normal]
## vim-like behavior
"{" = ["goto_prev_paragraph", "extend_visual_line_up"]
"}" = ["goto_next_paragraph"]
"0" = "extend_to_line_start"
"$" = "extend_to_line_end"
"^" = "extend_to_first_nonwhitespace"
"%" = ["collapse_selection", "select_mode", "match_brackets", "normal_mode"]
"-" = ":format"
C-r = "redo"
G = "goto_file_end"
D = "extend_to_line_end"
X = "extend_line_above"
V = ["select_mode", "extend_to_line_bounds"]

## Search for word under cursor
"*" = [
  "move_char_right",
  "move_prev_word_start",
  "move_next_word_end",
  "search_selection",
  "search_next",
]
"#" = [
  "move_char_right",
  "move_prev_word_start",
  "move_next_word_end",
  "search_selection",
  "search_prev",
]

## always i/a at current cursor position
i = ["collapse_selection", "insert_mode"]
a = ["collapse_selection", "append_mode"]

## personal preference
C-s = ":w"                # default: save_selection to jumplist (remapped to 'M')
M = "save_selection"
left = "jump_view_left"
right = "jump_view_right"
up = "jump_view_up"
down = "jump_view_down"

## lazygit support with A-g
A-g = [
  ":write-all",
  ":new",
  ":insert-output lazygit",
  ":buffer-close!",
  ":redraw",
  ":reload-all",
]

A-r = [
  ":write-all",
  ":insert-output scooter >/dev/tty",
  ":redraw",
  ":reload-all",
]

## Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "keep_primary_selection"]

[keys.select]
## vim-like behavior
"{" = ["goto_prev_paragraph", "extend_visual_line_up"]
"}" = ["goto_next_paragraph"]
"0" = "extend_to_line_start"
"$" = "extend_to_line_end"
"^" = "extend_to_first_nonwhitespace"
"%" = ["collapse_selection", "select_mode", "match_brackets", "normal_mode"]
"-" = ":format"
C-r = "redo"
G = "goto_file_end"
D = "extend_to_line_end"
X = "extend_line_above"
V = ["select_mode", "extend_to_line_bounds"]

## personal preference
C-s = ":w"
M = "save_selection"
left = "jump_view_left"
right = "jump_view_right"
up = "jump_view_up"
down = "jump_view_down"

## always i/a at current cursor position
i = ["collapse_selection", "insert_mode"]
a = ["collapse_selection", "append_mode"]

## Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

[keys.insert]
C-s = ["collapse_selection", "keep_primary_selection", "normal_mode", ":w"]
C-x = "completion"

## <See template file for keys.normal.space>
