### === this file is a chezmoi template ===
### docs (support): https://helix-editor.vercel.app/configuration/languages
### language support (docs): https://docs.helix-editor.com/lang-support.html
### defaults (github file): https://github.com/helix-editor/helix/blob/master/languages.toml
### recipes (wiki): https://github.com/helix-editor/helix/wiki/Language-Server-Configurations
[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }


[[language]]
name = "fish"
language-servers = [ "fish-lsp" ]

[language-server.fish-lsp]
command = "fish-lsp"
args= ["start"]
environment = { "fish_lsp_show_client_popups" = "false" }


[[language]]
name = "just"
language-servers = [ "just-lsp" ]

[language-server.just-lsp]
command = "just-lsp"
args= [""]


[[language]]
name = "xml"
file-types = [ "xml", "svg", "xsd", "xslt", "xsl" ]
formatter = { command = "xmllint", args = ["--format", "-"] }
language-servers = [ "xml" ]

[language-server.xml]
command = "lemminx-linux"


[language-server.yaml-language-server.config.yaml.schemas]
"https://json.schemastore.org/mprocs-0.6.4.json" = "mprocs.yaml"


[[language]]
name = "nix"
formatter = { command = "nixpkgs-fmt" }
