---
services:
  memos:
    container_name: memos
    restart: unless-stopped
    env_file: ".env"
    ports:
      - ${MEMOS_PORT}:5230
    volumes:
      - ${DOCKER_PERSIST}/memos/:/var/opt/memos
    image: neosmemo/memos:stable
