# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=,preferred,auto,auto
monitor=DP-1, 2560x1440@170, -0x770, 1  # GIGA-BYTE M27Q, but commas causes syntax error. fixed in future pr?
monitor=desc:LG SDQHD 208NTBK6R077, 2560x2880@60, 2560x0, 1
