# Execute your favorite apps at launch
exec-once = bash ~/.config/hypr/conf/start.sh
exec-once = obsidian &
exec-once = wl-paste -t text --watch clipman store --no-persist   ### what does this do?
# env deson't seem to be doing cursor size so do it here
exec-once = hyprctl setcursor Bibata-Modern-Ice 40

# can't figure out how to get order correct, just manually rearrange for now
exec-once=[workspace 2 silent] foot zellij
exec-once=[workspace 2 silent] code
exec-once=[workspace 3 silent] microsoft-edge
exec-once=[workspace 4 silent] firefox