# Execute your favorite apps at launch
exec-once = bash ~/.config/hypr/conf/start.sh
exec-once = obsidian &
exec-once = wl-paste -t text --watch clipman store --no-persist   ### what does this do?

# exec-once=[workspace 1 silent] kitty
# exec-once=[workspace 1 silent] subl
# exec-once=[workspace 3 silent] mailspring
# exec-once=[workspace 4 silent] firefox