# Execute your favorite apps at launch

# # batch script for services
exec-once = bash ~/.config/hypr/conf/start.sh

# # individual apps (put here to ensure window-rules)
exec-once = obsidian &
exec-once = signal --start-in-tray &

# # todo: see if hyprctl can order foot / code order
exec-once=[workspace 2 silent] foot zellij
exec-once=[workspace 2 silent] code
exec-once=[workspace 3 silent] microsoft-edge
exec-once=[workspace 4 silent] firefox

# # misc
exec-once = wl-paste -t text --watch clipman store --no-persist   ### what does this do?
# # env deson't seem to be doing cursor size so do it here
exec-once = hyprctl setcursor Bibata-Modern-Ice 40
