# Example windowrule v1

### obsidian
windowrule = workspace special:magic silent,^(obsidian)$
# windowrule = float,^(obsidian)$
windowrule = size 800 1000,^(obsidian)$
windowrule = center,^(obsidian)$

# windowrule = workspace 1 silent,microsoft-edge

# common modals
windowrule = float,title:^(Open)$
windowrule = float,title:^(Choose Files)$
windowrule = float,title:^(Save As)$
windowrule = float,title:^(Confirm to replace files)$
windowrule = float,title:^(File Operation Progress)$

# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
