# # Obsidian
windowrule = workspace special:magic silent,^(obsidian)$
# windowrule = float,^(obsidian)$
# windowrule = size 800 1000,^(obsidian)$
# windowrule = center,^(obsidian)$

windowrule = float,title:^(Waydroid)$
windowrule = float,title:^(Volume Control)$ # pavucontrol

# common modals
windowrule = float,title:^(Open)$
windowrule = float,title:^(Choose Files)$
windowrule = float,title:^(Save As)$
windowrule = float,title:^(Confirm to replace files)$
windowrule = float,title:^(File Operation Progress)$