# # For more info see hyprctl clients | nvim -

# # imported
windowrule = noblur,.*  # Disables blur for windows. Substantially improves performance.

# # Float
windowrule = float,title:^(Waydroid)$
windowrule = float,title:^(Volume Control)$ # pavucontrol
windowrule = float,title:^(bitwarden)$

# # Workspaces
# # 1: Blank 2: Editor / Terminal 3: microsoft-edge
# # 4: firefox
# # S: Obsidian

# # Microsoft edge
windowrulev2 = workspace 3 silent,class:(microsoft-edge)
# # ms-edge webapps (e.g. youtube)
windowrulev2 = float,class:(^msedge)
windowrulev2 = size 1000 800,class:(^msedge)
windowrulev2 = workspace special:magic,class:(^msedge),title:(^YouTube$)
windowrulev2 = tile,class:(^msedge),title:(^YouTube$)

# # Obsidian
windowrule = workspace special:magic silent,^(obsidian)$
# windowrule = float,^(obsidian)$
# windowrule = size 800 1000,^(obsidian)$
# windowrule = center,^(obsidian)$

# # Signal
# # initialTitle can be Signal (1) on notification
windowrulev2 = float,class:(signal),title:^(Signal) 
windowrule = size 800 1000,^(obsidian)$
windowrule = center,^(obsidian)$

# # VS Code
windowrulev2 = workspace 2 silent,class:(code-url-handler)

# # Common Modals
windowrule = float,title:^(Choose Files)(.*)$
windowrule = float,title:^(Open File)(.*)$
windowrule = float,title:^(Confirm to replace files)(/*)$
windowrule = float,title:^(File Operation Progress)(/*)$
windowrule = float,title:^(Select a File)(.*)$
windowrule = float,title:^(Choose wallpaper)(.*)$
windowrule = float,title:^(Open Folder)(.*)$
windowrule = float,title:^(Save As)(.*)$
windowrule = float,title:^(Library)(.*)$ 