### core
brew "atuin"
brew "bat"
brew "chezmoi"
brew "difftastic"
brew "eza"
brew "fd"
brew "fish"
brew "gh"
brew "grc"
brew "helix"
brew "just"
brew "lazydocker"
brew "lazygit"
brew "lolcat"
brew "mergiraf"
brew "mise" ### packaging
brew "mosh"
brew "mprocs"
brew "navi"
brew "nushell"
brew "pnpm"
brew "serpl" ### find and replace
brew "speedtest-cli"
brew "starship"
brew "tealdeer"
brew "television"
brew "uutils-coreutils"
brew "wget"
brew "yazi"
brew "zellij"
brew "zoxide"

### language servers
brew "bash-language-server"
brew "lua-language-server"
brew "marksman" ### markdown
brew "tailwindcss-language-server"
brew "taplo" ### toml
brew "typescript-language-server"
brew "vscode-langservers-extracted" ### HTML/CSS/JSON/ESlint
brew "yaml-language-server"
